# -*- coding: utf-8 -*-
SIGNALS_LOGIC = {'М1': {'type': 'SIG', 'node_id': '82', 'PrevSec': 'НП', 'NextSec': '1-7СП'},
 'М2': {'type': 'SIG', 'node_id': '38', 'PrevSec': 'ЧП', 'NextSec': '2-8СП'},
 'М3': {'type': 'SIG', 'node_id': '95', 'PrevSec': 'НДП', 'NextSec': '3СП'},
 'М4': {'type': 'SIG', 'node_id': '55', 'PrevSec': 'ЧДП', 'NextSec': '4СП'},
 'Н': {'type': 'LATE_SIG', 'node_id': '78', 'PrevSec': None, 'NextSec': 'НП'},
 'Н1': {'type': 'LATE_SIG', 'node_id': '46', 'PrevSec': '1АП', 'NextSec': '4СП'},
 'Н2': {'type': 'LATE_SIG', 'node_id': '61', 'PrevSec': '2АП', 'NextSec': '6СП'},
 'Н4': {'type': 'LATE_SIG', 'node_id': '64', 'PrevSec': '4П', 'NextSec': '2-8СП'},
 'НД': {'type': 'LATE_SIG', 'node_id': '100', 'PrevSec': None, 'NextSec': 'НДП'},
 'НМ1': {'type': 'LATE_SIG', 'node_id': '107', 'PrevSec': '1П', 'NextSec': '10-12СП'},
 'НМ2': {'type': 'LATE_SIG', 'node_id': '89', 'PrevSec': '2П', 'NextSec': '14-16СП'},
 'НМ3': {'type': 'LATE_SIG', 'node_id': '103', 'PrevSec': '3П', 'NextSec': '10-12СП'},
 'Ч': {'type': 'LATE_SIG', 'node_id': '42', 'PrevSec': None, 'NextSec': 'ЧП'},
 'Ч1': {'type': 'LATE_SIG', 'node_id': '114', 'PrevSec': '1П', 'NextSec': '1-7СП'},
 'Ч2': {'type': 'LATE_SIG', 'node_id': '92', 'PrevSec': '2П', 'NextSec': '3СП'},
 'Ч3': {'type': 'LATE_SIG', 'node_id': '117', 'PrevSec': '3П', 'NextSec': '1-7СП'},
 'ЧД': {'type': 'LATE_SIG', 'node_id': '53', 'PrevSec': None, 'NextSec': 'ЧДП'},
 'ЧМ1': {'type': 'LATE_SIG', 'node_id': '50', 'PrevSec': '1АП', 'NextSec': '10-12СП'},
 'ЧМ2': {'type': 'LATE_SIG', 'node_id': '68', 'PrevSec': '2АП', 'NextSec': '14-16СП'},
 'ЧМ4': {'type': 'LATE_SIG', 'node_id': '75', 'PrevSec': '4П', 'NextSec': '14-16СП'}}